info: 
  info: 工具项目
  
spring:
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss 
  rabbitmq:
    host: server-rabbitmq-aec
    port: 5672    #5672
    username: admin
    password: admin
    connection-timeout: 15000
    # 发送确认
    publisher-confirms: true
    # 路由失败回调
    publisher-returns: true
    template:
      # 必须设置成true 消息路由失败通知监听者，而不是将消息丢弃
      mandatory: true

  datasource:
    url: jdbc:mysql://192.168.0.249:3306/cscec-third?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    url: tcp://server-redis-aec:6379
    database: 0
    timeout: 3000
    pool:
      max-active: 600  # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽) 
      max-wait: 1000   # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-idle: 300    # 连接池中的最大空闲连接，默认值也是8
      min-idle: 30     # 连接池中的最小空闲连接，默认值也是0
  session:
    store-type: none
eureka:
  client:
   healthcheck:
      enable: false
    
management:
  security:
    enabled: false
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

ycloud:
  spring:
    cors:
      enabled: true
      
          
swagger2:
  base-package: com.dpi.outInterface
  verison: 1.0.0
  title: 对外第三方接口
  customized-variables:
  - name: Authorization
    description: 令牌
    model-ref: string
    type: header  

appkey: 'HGmUJOS3zjGSxyKjkBXMPxpx6eVv5kvWe4N'

third:
  config:
    customer:
      url: http://221.214.64.195:9019/
      #url: http://khfw.cscec8b.com.cn/
      clientid: KHFW0216
      secret: khfw*81-ab84692d
      granttype: client_credentials
    local:
      url: http://150.138.227.43:8081/
      #url: http://210.13.83.62:7659/
      soap-action: http://tempuri.org/
      str-key: 6B9CDDD87C914C69A7EC8725BCCE4CBD
      #str-key: 9967AF39-26A3-43E2-A1D0-06DFD4BD9252
    quality:
      #url: http://autobuild.jiguantong.com:8087
      url: http://app.cscec8b.com.cn
      secretKey: 4c3eb58ce66e7fae22e1b6832d931be1
    hr:
      key: 1111

com:
  ibm:
    ws:
      webcontainer:
        invokeFlushAfterService: false